from modules.nethelper import pretty


class SystemInfoGatherer:
    def __init__(self):
        # System info
        self.system_info = None
        self.hostname = None
        self.lsb_release = None
        self.current_user = None
        self.user_id = None
        self.last_logged_in = None
        self.who_is_on = None
        self.disk_usage = None
        self.directory_usage = None
        self.setuid_files = None
        self.list_files = None
        self.current_processes = None
        self.top_processes = None
        self.open_files = None
        self.network_info = None
        self.network_stats = None
        self.socket_stats = None
        self.ip_address = None
        self.running_services = None
        self.service_status = None
        self.installed_packages = None
        self.scheduled_tasks = None
        self.scheduled_at_jobs = None
        self.system_logs = None
        self.boot_logs = None
        self.env_vars = None
        self.home_dir = None

        # Binaries
        self.is_sudo = None
        self.is_su = None
        self.is_find = None
        self.is_awk = None
        self.is_nmap = None
        self.is_python = None
        self.is_perl = None
        self.is_ruby = None
        self.is_php = None
        self.is_less = None
        self.is_more = None
        self.is_nano = None
        self.is_vi = None
        self.is_vim = None
        self.is_man = None
        self.is_bash = None
        self.is_sh = None
        self.is_csh = None
        self.is_cp = None
        self.is_mv = None
        self.is_ln = None
        self.is_rm = None
        self.is_chmod = None
        self.is_chown = None
        self.is_chgrp = None
        self.is_passwd = None
        self.is_chsh = None
        self.is_newgrp = None
        self.is_cron = None
        self.is_at = None
        self.is_batch = None
        self.is_tcpdump = None
        self.is_mysql = None
        self.is_postgres = None
        self.is_gdb = None
        self.is_strace = None
        self.is_netcat = None
        self.is_ncat = None
        self.is_nc = None
        self.is_bash_shell = None
        self.is_perl_shell = None
        self.is_python = None
        self.is_python3 = None
        self.is_php_shell = None
        self.is_ruby_shell = None
        self.is_socat = None
        self.is_telnet = None
        self.is_openssl = None

    def sysGatherer(self, sock):
        self.system_info = pretty(sock.send_command("uname -a"))
        self.hostname = pretty(sock.send_command("hostname"))
        self.lsb_release = pretty(sock.send_command("lsb_release -a"))
        self.current_user = pretty(sock.send_command("whoami"))
        self.user_id = pretty(sock.send_command("id"))
        self.last_logged_in = pretty(sock.send_command("last"))
        self.who_is_on = pretty(sock.send_command("w"))
        self.disk_usage = pretty(sock.send_command("df -h"))
        self.directory_usage = pretty(sock.send_command("du -sh"))
        self.setuid_files = pretty(sock.send_command("find / -perm -4000 2>/dev/null"))
        self.list_files = pretty(sock.send_command("ls -lah"))
        self.current_processes = pretty(sock.send_command("ps aux"))
        self.top_processes = pretty(sock.send_command("top -b -n 1"))
        self.open_files = pretty(sock.send_command("lsof -i"))
        self.network_info = pretty(sock.send_command("ifconfig"))
        self.network_stats = pretty(sock.send_command("netstat -tuln"))
        self.socket_stats = pretty(sock.send_command("ss -tuln"))
        self.ip_address = pretty(sock.send_command("ip addr"))
        self.running_services = pretty(sock.send_command("systemctl list-units --type=service"))
        self.service_status = pretty(sock.send_command("service --status-all"))
        self.installed_packages = pretty(sock.send_command("dpkg -l"))  # for Debian-based systems
        self.scheduled_tasks = pretty(sock.send_command("crontab -l"))
        self.scheduled_at_jobs = pretty(sock.send_command("at -l"))
        self.system_logs = pretty(sock.send_command("journalctl"))
        self.boot_logs = pretty(sock.send_command("dmesg"))
        self.env_vars = pretty(sock.send_command("env"))
        self.home_dir = pretty(sock.send_command("printenv HOME"))

    def binaryGatherer(self, sock):
        self.is_sudo = pretty(sock.send_command("which sudo"))
        self.is_su = pretty(sock.send_command("which su"))
        self.is_find = pretty(sock.send_command("which find"))
        self.is_awk = pretty(sock.send_command("which awk"))
        self.is_nmap = pretty(sock.send_command("which nmap"))
        self.is_python = pretty(sock.send_command("which python"))
        self.is_perl = pretty(sock.send_command("which perl"))
        self.is_ruby = pretty(sock.send_command("which ruby"))
        self.is_php = pretty(sock.send_command("which php"))
        self.is_less = pretty(sock.send_command("which less"))
        self.is_more = pretty(sock.send_command("which more"))
        self.is_nano = pretty(sock.send_command("which nano"))
        self.is_vi = pretty(sock.send_command("which vi"))
        self.is_vim = pretty(sock.send_command("which vim"))
        self.is_man = pretty(sock.send_command("which man"))
        self.is_bash = pretty(sock.send_command("which bash"))
        self.is_sh = pretty(sock.send_command("which sh"))
        self.is_csh = pretty(sock.send_command("which csh"))
        self.is_cp = pretty(sock.send_command("which cp"))
        self.is_mv = pretty(sock.send_command("which mv"))
        self.is_ln = pretty(sock.send_command("which ln"))
        self.is_rm = pretty(sock.send_command("which rm"))
        self.is_chmod = pretty(sock.send_command("which chmod"))
        self.is_chown = pretty(sock.send_command("which chown"))
        self.is_chgrp = pretty(sock.send_command("which chgrp"))
        self.is_passwd = pretty(sock.send_command("which passwd"))
        self.is_chsh = pretty(sock.send_command("which chsh"))
        self.is_newgrp = pretty(sock.send_command("which newgrp"))
        self.is_cron = pretty(sock.send_command("which cron"))
        self.is_at = pretty(sock.send_command("which at"))
        self.is_batch = pretty(sock.send_command("which batch"))
        self.is_tcpdump = pretty(sock.send_command("which tcpdump"))
        self.is_mysql = pretty(sock.send_command("which mysql"))
        self.is_postgres = pretty(sock.send_command("which postgres"))
        self.is_gdb = pretty(sock.send_command("which gdb"))
        self.is_strace = pretty(sock.send_command("which strace"))
        self.is_netcat = pretty(sock.send_command("which netcat"))
        self.is_ncat = pretty(sock.send_command("which ncat"))
        self.is_nc = pretty(sock.send_command("which nc"))
        self.is_bash_shell = pretty(sock.send_command("which bash"))
        self.is_perl_shell = pretty(sock.send_command("which perl"))
        self.is_python = pretty(sock.send_command("which python"))
        self.is_python3 = pretty(sock.send_command("which python3"))
        self.is_php_shell = pretty(sock.send_command("which php"))
        self.is_ruby_shell = pretty(sock.send_command("which ruby"))
        self.is_socat = pretty(sock.send_command("which socat"))
        self.is_telnet = pretty(sock.send_command("which telnet"))
        self.is_openssl = pretty(sock.send_command("which openssl"))